spring:
  datasource:
    url: jdbc:db2://localhost:50000/testdb
    username: db2inst1
    password: password
    driverClassName: com.ibm.db2.jcc.DB2Driver
    dbcp2:
      validation-query: SELECT 1
      test-while-idle: true
      cache-state: true
  jpa:
    show-sql: true
    generate-ddl: false
    database-platform: DB2Platform
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DB2Dialect
    open-in-view: false
  mvc:
    view:
      prefix: /WEB-INF/view
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: false
storage:
  location: newFolder
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%10.15t]){faint} %clr(%-40.40logger{39}:%-3.3line){cyan} %clr(:){faint} %m%n"