version: "3.7"
services:
  mydb2:
    privileged: true
    container_name: mydb2
    image: ibmcom/db2
#    build:
#      context: ./db2
#      dockerfile: Dockerfile
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: password
      DBNAME: testdb
    networks:
      - default
    ports:
      - "50000:50000"
    volumes:
      - "dbdata:/database:rw"
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - "8080:8080"
    depends_on:
      - mydb2

networks:
  default:

volumes:
  dbdata: