version: "3.7"
services:

  db2:
    image: ibmcom/db2:latest
    build:
      dockerfile: db2/Dockerfile
    
      ports:
        - "50000"
      networks:
        - backend
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      

networks:
  backend:

volumes:
  db-data: